title: ATROTOS # name of the site
author: George Violaris # name of site's author
email: violarisgeorge@gmail.com # email of site's author
url: https://atrotos.net # root address of the site
#baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A collection of articles, resources, random thoughts, quick notes,
  and everything and anything that I have learned or would like to expand
  my knowledge in. I like technology, artificial intelligence, decentralized systems,
  distributed knowledge, economics, philosophy and any possible intertwining
  of such subjects and ideas.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
